use crate::domain::entities::{InitOptions, ProjectLanguage, TopologyKind};
use crate::domain::errors::CliError;
use std::path::PathBuf;

const RUST_CARGO: &str = include_str!("../../templates/rust/Cargo.toml.hbs");
const RUST_MAIN: &str = include_str!("../../templates/rust/main.rs.hbs");
const RUST_NODE: &str = include_str!("../../templates/rust/node.rs.hbs");
const PYTHON_NODE: &str = include_str!("../../templates/python/node.py.hbs");
const PYTHON_REQUIREMENTS: &str = include_str!("../../templates/python/requirements.txt.hbs");
const PYTHON_TEST: &str = include_str!("../../templates/python/test_agent.py.hbs");
const TYPESCRIPT_MAIN: &str = include_str!("../../templates/typescript/index.ts.hbs");
const DART_MAIN: &str = include_str!("../../templates/dart/main.dart.hbs");

pub fn render_common_files(options: &InitOptions) -> Result<Vec<(PathBuf, String)>, CliError> {
    Ok(vec![
        (
            PathBuf::from("orchustr.yaml"),
            format!(
                "orchustr_version: \"0.1.0\"\nproject:\n  name: {}\n  language: {}\n  provider: {}\n\ngraph:\n  $ref: ./graph.yaml\n\nobservability:\n  enabled: true\n  dashboard_port: 7700\n\nmcp_servers: []\n",
                options.project_name,
                language_name(options.language),
                options.provider.as_str()
            ),
        ),
        (
            PathBuf::from("graph.yaml"),
            render_graph_yaml(options.topology),
        ),
        (
            PathBuf::from(".env.example"),
            format!("{}=your_value_here\n", options.provider.env_key()),
        ),
        (
            PathBuf::from("README.md"),
            format!(
                "# {}\n\nGenerated by `or-cli`.\n\n- Language: {}\n- Topology: {}\n- Provider: {}\n",
                options.project_name,
                language_name(options.language),
                topology_name(options.topology),
                options.provider.as_str()
            ),
        ),
    ])
}

pub fn render_graph_yaml(topology: TopologyKind) -> String {
    match topology {
        TopologyKind::React => "name: simple-react-agent\nversion: \"0.1.0\"\nentry: think\nexits: [done]\nnodes:\n  - id: think\n    handler: nodes::think\n    metadata: {}\n  - id: act\n    handler: nodes::act\n    metadata: {}\n  - id: done\n    handler: nodes::done\n    metadata: {}\nedges:\n  - from: think\n    to: act\n  - from: act\n    to: done\n".to_owned(),
        TopologyKind::PlanExecute => "name: plan-execute-agent\nversion: \"0.1.0\"\nentry: plan\nexits: [done]\nnodes:\n  - id: plan\n    handler: nodes::plan\n    metadata: {}\n  - id: execute_step\n    handler: nodes::execute_step\n    metadata: {}\n  - id: done\n    handler: nodes::done\n    metadata: {}\nedges:\n  - from: plan\n    to: execute_step\n  - from: execute_step\n    to: done\n".to_owned(),
        TopologyKind::Reflection => "name: reflection-agent\nversion: \"0.1.0\"\nentry: draft\nexits: [accept]\nnodes:\n  - id: draft\n    handler: nodes::draft\n    metadata: {}\n  - id: critique\n    handler: nodes::critique\n    metadata: {}\n  - id: accept\n    handler: nodes::accept\n    metadata: {}\nedges:\n  - from: draft\n    to: critique\n  - from: critique\n    to: accept\n".to_owned(),
    }
}

pub fn render_rust_files(options: &InitOptions) -> Result<Vec<(PathBuf, String)>, CliError> {
    Ok(vec![
        (PathBuf::from("Cargo.toml"), render(RUST_CARGO, options)),
        (PathBuf::from("src/main.rs"), render(RUST_MAIN, options)),
        (PathBuf::from("src/nodes/mod.rs"), "pub mod think;\npub mod act;\n".to_owned()),
        (PathBuf::from("src/nodes/think.rs"), render_node(RUST_NODE, "think")),
        (PathBuf::from("src/nodes/act.rs"), render_node(RUST_NODE, "act")),
        (
            PathBuf::from("tests/integration_test.rs"),
            "#[test]\nfn generated_project_builds() {\n    assert!(true);\n}\n".to_owned(),
        ),
    ])
}

pub fn render_python_files(options: &InitOptions) -> Result<Vec<(PathBuf, String)>, CliError> {
    Ok(vec![
        (
            PathBuf::from("requirements.txt"),
            render(PYTHON_REQUIREMENTS, options),
        ),
        (PathBuf::from("nodes/think.py"), render_node(PYTHON_NODE, "think")),
        (PathBuf::from("nodes/act.py"), render_node(PYTHON_NODE, "act")),
        (PathBuf::from("tests/test_agent.py"), render(PYTHON_TEST, options)),
    ])
}

pub fn render_typescript_files(
    options: &InitOptions,
) -> Result<Vec<(PathBuf, String)>, CliError> {
    Ok(vec![(
        PathBuf::from("src/index.ts"),
        render(TYPESCRIPT_MAIN, options),
    )])
}

pub fn render_dart_files(options: &InitOptions) -> Result<Vec<(PathBuf, String)>, CliError> {
    Ok(vec![(
        PathBuf::from("lib/main.dart"),
        render(DART_MAIN, options),
    )])
}

fn render(template: &str, options: &InitOptions) -> String {
    template
        .replace("{{project_name}}", &options.project_name)
        .replace("{{language}}", language_name(options.language))
        .replace("{{provider}}", options.provider.as_str())
        .replace("{{provider_env}}", options.provider.env_key())
}

fn render_node(template: &str, name: &str) -> String {
    template.replace("{{node_name}}", name)
}

fn language_name(language: ProjectLanguage) -> &'static str {
    match language {
        ProjectLanguage::Rust => "rust",
        ProjectLanguage::Python => "python",
        ProjectLanguage::Typescript => "typescript",
        ProjectLanguage::Dart => "dart",
    }
}

fn topology_name(topology: TopologyKind) -> &'static str {
    match topology {
        TopologyKind::React => "react",
        TopologyKind::PlanExecute => "plan-execute",
        TopologyKind::Reflection => "reflection",
    }
}
