use crate::domain::entities::{
    InitOptions, OrchustrConfig, ProjectLanguage, RunRequest, RunSummary,
};
use crate::domain::errors::CliError;
use crate::infra::templates::{
    render_common_files, render_dart_files, render_python_files, render_rust_files,
    render_typescript_files,
};
use async_trait::async_trait;
use or_lens::start_dashboard_server;
use or_schema::GraphSpec;
use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};

/// Runtime hook used by `or-cli` to hand parsed project config to an executor.
#[async_trait]
pub trait ProjectRunner: Send + Sync {
    /// Executes a parsed Orchustr project request.
    async fn run(&self, request: RunRequest) -> Result<(), CliError>;
}

/// Default no-op runner used by the `orchustr` binary after config validation.
pub struct DefaultProjectRunner;

#[async_trait]
impl ProjectRunner for DefaultProjectRunner {
    async fn run(&self, _request: RunRequest) -> Result<(), CliError> {
        Ok(())
    }
}

/// Creates a new Orchustr project scaffold from the provided options.
pub fn init_project(options: &InitOptions) -> Result<PathBuf, CliError> {
    let root = options.project_root();
    if root.exists() {
        return Err(CliError::InvalidProject(format!(
            "project directory already exists: {}",
            root.display()
        )));
    }

    fs::create_dir_all(&root)?;
    for (relative, contents) in render_common_files(options)? {
        write_file(&root.join(relative), &contents)?;
    }
    for (relative, contents) in language_files(options)? {
        write_file(&root.join(relative), &contents)?;
    }
    Ok(root)
}

/// Validates an Orchustr project directory or a directory of graph examples.
pub fn lint_path(path: &Path) -> Result<Vec<PathBuf>, CliError> {
    if path.is_file() {
        return Ok(vec![validate_graph_file(path)?]);
    }
    let config_path = path.join("orchustr.yaml");
    if config_path.exists() {
        let config = load_config(path)?;
        let graph_path = config.graph_path(path);
        validate_graph_file(&graph_path)?;
        return Ok(vec![graph_path]);
    }

    let mut validated = Vec::new();
    for entry in fs::read_dir(path)? {
        let entry = entry?;
        let file = entry.path();
        let is_yaml = file
            .extension()
            .and_then(|value| value.to_str())
            .is_some_and(|value| matches!(value, "yaml" | "yml"));
        if is_yaml {
            validated.push(validate_graph_file(&file)?);
        }
    }
    if validated.is_empty() {
        return Err(CliError::InvalidProject(format!(
            "no graph yaml files found in {}",
            path.display()
        )));
    }
    Ok(validated)
}

/// Loads an Orchustr project and hands it to the provided runner implementation.
pub async fn run_project<R: ProjectRunner>(
    project_dir: &Path,
    runner: &R,
) -> Result<RunSummary, CliError> {
    let config = load_config(project_dir)?;
    let graph = load_graph(&config, project_dir)?;
    let request = RunRequest {
        project_dir: project_dir.to_path_buf(),
        config: config.clone(),
        graph,
    };
    runner.run(request).await?;
    Ok(RunSummary {
        project_name: config.project.name,
        dashboard_port: config
            .observability
            .enabled
            .then_some(config.observability.dashboard_port),
    })
}

/// Starts the local `or-lens` dashboard configured by an Orchustr project.
pub async fn trace_project(project_dir: &Path) -> Result<u16, CliError> {
    let config = load_config(project_dir)?;
    let port = config.observability.dashboard_port;
    let handle = start_dashboard_server(port)
        .await
        .map_err(|error| CliError::Lens(error.to_string()))?;
    let bound_port = handle.port();
    handle.shutdown();
    Ok(bound_port)
}

/// Scaffolds a node file inside an existing Orchustr project.
pub fn scaffold_node(project_dir: &Path, name: &str) -> Result<PathBuf, CliError> {
    let config = load_config(project_dir)?;
    let file_name = format!("{name}.{}", config.project.language.file_extension());
    let path = project_dir.join("nodes").join(file_name);
    let contents = config.project.language.node_template(name);
    write_file(&path, &contents)?;
    Ok(path)
}

/// Scaffolds a Rust `LoopTopology` stub inside an existing Orchustr project.
pub fn scaffold_topology(project_dir: &Path, name: &str) -> Result<PathBuf, CliError> {
    let path = project_dir.join(format!("{name}_topology.rs"));
    let contents = format!(
        "use or_core::DynState;\nuse or_loom::GraphBuilder;\nuse or_sentinel::LoopTopology;\n\n\
         /// Custom topology scaffold generated by `or-cli`.\n\
         pub struct {name}Topology;\n\n\
         impl LoopTopology for {name}Topology {{\n\
             fn build(&self) -> GraphBuilder<DynState> {{\n\
                 GraphBuilder::new()\n\
             }}\n\n\
             fn name(&self) -> &'static str {{\n\
                 \"{name}\"\n\
             }}\n\
         }}\n"
    );
    write_file(&path, &contents)?;
    Ok(path)
}

fn language_files(options: &InitOptions) -> Result<Vec<(PathBuf, String)>, CliError> {
    match options.language {
        ProjectLanguage::Rust => render_rust_files(options),
        ProjectLanguage::Python => render_python_files(options),
        ProjectLanguage::Typescript => render_typescript_files(options),
        ProjectLanguage::Dart => render_dart_files(options),
    }
}

fn load_config(project_dir: &Path) -> Result<OrchustrConfig, CliError> {
    let raw = fs::read_to_string(project_dir.join("orchustr.yaml"))?;
    serde_yaml::from_str(&raw).map_err(|error| CliError::Config(error.to_string()))
}

fn load_graph(config: &OrchustrConfig, project_dir: &Path) -> Result<GraphSpec, CliError> {
    let graph_path = config.graph_path(project_dir);
    let raw = fs::read_to_string(&graph_path)?;
    let graph = if graph_path
        .extension()
        .and_then(|value| value.to_str())
        .is_some_and(|value| value.eq_ignore_ascii_case("json"))
    {
        GraphSpec::from_json(&raw)?
    } else {
        GraphSpec::from_yaml(&raw)?
    };
    validate_graph_spec(&graph)?;
    Ok(graph)
}

fn validate_graph_file(path: &Path) -> Result<PathBuf, CliError> {
    let raw = fs::read_to_string(path)?;
    let graph = if path
        .extension()
        .and_then(|value| value.to_str())
        .is_some_and(|value| value.eq_ignore_ascii_case("json"))
    {
        GraphSpec::from_json(&raw)?
    } else {
        GraphSpec::from_yaml(&raw)?
    };
    validate_graph_spec(&graph)?;
    Ok(path.to_path_buf())
}

fn validate_graph_spec(graph: &GraphSpec) -> Result<(), CliError> {
    let nodes = graph.nodes.iter().map(|node| node.id.clone()).collect::<HashSet<_>>();
    if !nodes.contains(&graph.entry) {
        return Err(CliError::Validation(format!(
            "entry node '{}' is not declared",
            graph.entry
        )));
    }
    if graph.exits.is_empty() {
        return Err(CliError::Validation("graph must declare at least one exit node".to_owned()));
    }
    for exit in &graph.exits {
        if !nodes.contains(exit) {
            return Err(CliError::Validation(format!(
                "exit node '{}' is not declared",
                exit
            )));
        }
    }
    for edge in &graph.edges {
        if !nodes.contains(&edge.from) || !nodes.contains(&edge.to) {
            return Err(CliError::Validation(format!(
                "edge '{}' -> '{}' references an unknown node",
                edge.from, edge.to
            )));
        }
    }
    Ok(())
}

fn write_file(path: &Path, contents: &str) -> Result<(), CliError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents)?;
    Ok(())
}
