def version() -> str: ...
def render_prompt_json(template: str, context_json: str) -> str: ...
def normalize_state_json(raw_state: str) -> str: ...
def workspace_catalog_json() -> str: ...
def invoke_crate_json(crate_name: str, operation: str, payload_json: str) -> str: ...
