from typing import Any


def version() -> str: ...
def render_prompt_json(template: str, context_json: str) -> str: ...
def normalize_state_json(raw_state: str) -> str: ...
def workspace_catalog_json() -> str: ...
def invoke_crate_json(crate_name: str, operation: str, payload_json: str) -> str: ...


class PyDynState:
    def __init__(self, initial: dict[str, Any] | None = None) -> None: ...
    def __getitem__(self, key: str) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def get(self, key: str) -> Any: ...
    def to_dict(self) -> dict[str, Any]: ...
    def keys(self) -> list[str]: ...


class PyNodeResult:
    kind: str
    next: str | None

    @staticmethod
    def advance(state: PyDynState) -> "PyNodeResult": ...
    @staticmethod
    def exit(state: PyDynState) -> "PyNodeResult": ...
    @staticmethod
    def branch(state: PyDynState, next: str) -> "PyNodeResult": ...
    @staticmethod
    def pause(checkpoint_id: str, state: PyDynState) -> "PyNodeResult": ...


class PyPromptTemplate:
    def render(self, context: Any) -> Any: ...


class PyPromptBuilder:
    def __init__(self) -> None: ...
    def template(self, template: str) -> None: ...
    def build(self) -> PyPromptTemplate: ...


class PyExecutionGraph:
    def entry(self) -> str: ...
    def exit(self) -> str: ...
    def node_names(self) -> list[str]: ...
    def edge_targets(self, node: str) -> list[str]: ...
    def get_handler(self, node: str) -> Any: ...


class PyGraphBuilder:
    def __init__(self) -> None: ...
    def add_node(self, name: str, handler: Any) -> None: ...
    def add_edge(self, source: str, target: str) -> None: ...
    def set_entry(self, name: str) -> None: ...
    def set_exit(self, name: str) -> None: ...
    def build(self) -> PyExecutionGraph: ...


class PyPipeline:
    def node_names(self) -> list[str]: ...


class PyPipelineBuilder:
    def __init__(self) -> None: ...
    def add_node(self, name: str, handler: Any) -> None: ...
    def build(self) -> PyPipeline: ...


class PyConduitProvider:
    def __init__(self, label: str | None = None) -> None: ...
    @property
    def label(self) -> str | None: ...


class PyForgeRegistry:
    def __init__(self) -> None: ...
    def register(self, name: str, handler: Any) -> None: ...
    def len(self) -> int: ...
    def tool_names(self) -> list[str]: ...


class PyColonyBuilder:
    def __init__(self) -> None: ...
    def add_member(self, name: str, role: str) -> None: ...
    def member_names(self) -> list[str]: ...


class PyRelayPlan:
    def branch_names(self) -> list[str]: ...


class PyRelayBuilder:
    def __init__(self) -> None: ...
    def add_branch(self, name: str, handler: Any) -> None: ...
    def build(self) -> PyRelayPlan: ...
